- swagger-omnichat-api.yaml
Documentation Updated, added labels to the chat definition
> DES-111 Documentation Updated, added labels to the chat definition

- swagger-omnichat-api.yaml
[S3-3270](https://omnichat.atlassian.net/browse/S3-3270)
Alteração do nome do atributo **descrição** na aba Criar Produto. Estava com productDescription foi alterado para description.
Antes  | Depois
------------- | -------------
> fix: change attribute name description in /products

- swagger-omnichat-api.yaml
[SES-204](https://omnichat.atlassian.net/browse/SES-204)
Atualiza a documentação com depreciação de rotas, filtros e novos padrões de busca, ordenação e limites.
> FEAT: SES-204 update docs, add new filters, deprecate routes and filters - PROD

- swagger-omnichat-api.yaml
[SES-378](https://omnichat.atlassian.net/browse/SES-378)
Atualiza Message Model para refletir o que `Translator` realmente retorna no payload, adiciona `RoutedToTeam` e `RoutedToUser` Types
- FEAT: Add return of `routedToUser`, `routedToTeam` on Message Model
- CHORE: Updates docs removing unreturned keys on Message Model:
- isCreatingNewChat
- note
- readBy
- snoozedUntil
- quotedMessage
- variant
> FEAT: Add RoutedToTeam, RoutedToUser - PROD

- swagger-omnichat-api.yaml
[ECI-226](https://omnichat.atlassian.net/browse/ECI-226)
- Adicionando `externalId` a documentação da API pública.
> feat: ECI-226

- swagger-omnichat-api.yaml
N/A
Adicionado a prorpriedade origin no swagger.
> chore: add origin to swagger

- swagger-omnichat-api.yaml
[AR-192](https://omnichat.atlassian.net/browse/AR-192)
Incluído campaignId e contactOrigin nas configurações da message
> fix: updated swagger config to include campaignId e contactOrigin

- swagger-omnichat-api.yaml
[S3-5882](https://omnichat.atlassian.net/browse/S3-5882)
Adiciona o campo `salesPersonCode` no payload da requisição /users (POST) para criação do usuário.
> feat: S3-5882

- swagger-omnichat-api.yaml
> chore: documentation

- swagger-omnichat-api.yaml
> feat: update docs

- swagger-omnichat-api.yaml
[ECI-600](https://omnichat.atlassian.net/browse/ECI-600)
Atualiza o swagger com a URL da imagem de avatar do usuário.
> adds picture field on user return

- dev-swagger-omnichat-api.yaml
[ECI-600](https://omnichat.atlassian.net/browse/ECI-600)
Atualiza swagger de dev com campo picture do usuário.
> fix: update swagger dev

- swagger-omnichat-api.yaml
N/A
Adiciona a documentação de ordenação por updatedAt no /chats
> feat: new sorting

- swagger-omnichat-api.yaml
N/A
Corrigindo bug do título do Listr Chats estar bugado.
> fix: list chats broken title

- swagger-omnichat-api.yaml
[S3-9958](https://omnichat.atlassian.net/browse/S3-9958)
Adiciona `forceSend` e`context` na rota de enviar mensagem.
[S3-9958]: https://omnichat.atlassian.net/browse/S3-9958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add `forceSend` and `context` to doc

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[AT-2606](https://omnichat.atlassian.net/browse/AT-2606)
Adiciona `teamGroups` da listagem de times.
[AT-2606]: https://omnichat.atlassian.net/browse/AT-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add `teamGroups` list to teams

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[S3-10206](https://omnichat.atlassian.net/browse/S3-10206)
Atualiza documentação referente a atualização de times.
[S3-10206]: https://omnichat.atlassian.net/browse/S3-10206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update doc update team

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[SP-526](https://omnichat.atlassian.net/browse/SP-526)
Atualiza a documentação de API referente a listagem de clientes.
[SP-526]: https://omnichat.atlassian.net/browse/SP-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update doc list customers

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[AT-3309](https://omnichat.atlassian.net/browse/AT-3309)
Atualiza a documentação da listagem de mensagens, incluindo o campo `reactions`.
[AT-3309]: https://omnichat.atlassian.net/browse/AT-3309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add field reactions to list messages

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[AT-2729](https://omnichat.atlassian.net/browse/AT-2729)
Adiciona o campo pipelineStage na rota de Chat.
[AT-2729]: https://omnichat.atlassian.net/browse/AT-2729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: adds pipelineStage to chat route

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[AT-3376](https://omnichat.atlassian.net/browse/AT-3376)
- Adiciona o campo `supportRateComment` ao retorno da API de `Interactions`
[AT-3376]: https://omnichat.atlassian.net/browse/AT-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add supportRateComment to Interactions API

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[AT-2729](https://omnichat.atlassian.net/browse/AT-2729)
Corrige definição do pipeline.
[AT-2729]: https://omnichat.atlassian.net/browse/AT-2729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fixes pipeline definition

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[AT-3939](https://omnichat.atlassian.net/browse/AT-3939)
Adiciona novos campos em time, `isAutomaticDistributionEnabled` e `automaticDistributionCapacity`.
[AT-3939]: https://omnichat.atlassian.net/browse/AT-3939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add new fields team `isAutomaticDistributionEnabled` and `automaticDistributionCapacity`

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[SC-1453](https://omnichat.atlassian.net/browse/SC-1453)
Busca por externalId na lista de pedidos
[SC-1453]: https://omnichat.atlassian.net/browse/SC-1453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add externalId in get orders list

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[SC-1494](https://omnichat.atlassian.net/browse/SC-1494)
- Adicionando sellerId no Item do pedido
[SC-1494]: https://omnichat.atlassian.net/browse/SC-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add sellerId field to API definitions

- dev-swagger-omnichat-api.yaml
- swagger-omnichat-api.yaml
[SAL-454](https://omnichat.atlassian.net/browse/SAL-454)
Adicionar a possibilidade de enviar audio na API pública da Omni.
[SAL-454]: https://omnichat.atlassian.net/browse/SAL-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add audio type with attachment url to send new messages
